### ISSUE TITLE
Use object literal

### ISSUE THREAD

**Issue by monolithed** [indexzero/nconf#158] opened 2015-04-13 23:56 UTC
```js
nconf.set({x: 1, y: 2});
nconf.get('x'); // 1
```

it would be pretty cool if you did

**Comment by grabbou** [comment] 2015-05-14 09:50
Try `nconf.defaults({x: 1, y: 2})`

**Comment by mikkotikkanen** [comment] 2015-06-09 12:03
However...

```js
nconf.defaults({x: 1, y: 2});
nconf.defaults({x: 10});
```

... doesn't work as the latter seem to override the former completely

**Comment by mikkotikkanen** [comment] 2015-07-01 07:02
This, however, seems to work:

```js
nconf.use('myobject', { type: 'literal', store: {x: 1, y: 2} })
nconf.defaults({x: 10});
```

**Comment by indexzero** [comment] 2015-09-20 08:25
Duplicate of #154.

**Closed by indexzero** 2015-09-20 08:25 UTC
