### ISSUE TITLE
Comments in a config file

### ISSUE THREAD

**Issue by otruffer** [indexzero/nconf#113] opened 2014-03-20 15:06 UTC
Hi there,

First of all: thanks for this handy tool! Now, my issue: I would like to add some comments into my config file which by default is not json standard. In the case of a config json file this would make sense though imho (see e.g. http://blog.getify.com/json-comments/).

Using JSON.minify, this would be implementable with ease:
https://github.com/getify/JSON.minify

Thanks for the consideration & cheers.

**Comment by laktak** [comment] 2015-01-14 21:52
You can do this with
```
nconf.file({ file: 'file.json', format: require('hjson') });
```
[Hjson](laktak.github.io/hjson) also make quotes and commas optional.

**Comment by davelnewton** [comment] 2015-01-14 21:55
Nice; I think that's the equivalent of mine wrt the parsing; I did a couple other things in that snippet.

**Comment by indexzero** [comment] 2015-09-20 08:35
Passing another module in as the format is the accepted way of doing things. `nconf` cannot support every file format in the world. It would have an impossibly bloated set of dependencies. Going to make this as a documentation bug and duplicate of #160 because we can (and will) be much clearer about the right way to do things in the docs.

**Closed by indexzero** 2015-09-20 08:35 UTC
