### ISSUE TITLE
Deleting a file after removing the transport 

### ISSUE THREAD

**Issue by monolithed** [indexzero/nconf#159] opened 2015-04-19 12:50 UTC
```js
var fs    = require('fs'),
	path  = require('path'),
	nconf = require('nconf');

var file = './settings.json';

nconf.use('file', {
	file: path.resolve(file)
});

nconf.set('foo', true);
nconf.save();

nconf.remove('file');

console.log(nconf.get('foo'), require(file).foo); // undefined, true
```

It is not obvious that the file can not be deleted.

Real problem:

```js
class Foo {
  constructor (options) {
      set_options(options); // a wrapper around nconf
  }
}

new Foo({foo: 0});
new Foo({bar: 1});

require(file) // {foo: 0, bar: 1} ??? I don't want to keep all options
```

@indexzero, could you provide a flag like 
`nconf.remove('file', true)` or `nconf.use({remove: true})`?

**Comment by indexzero** [comment] 2015-09-20 08:28
Duplicate of #154.

**Closed by indexzero** 2015-09-20 08:28 UTC
